That line was way too spammy.
Second time I'm committing this because I just lack the amount of Stockholm Syndrome to understand the endless BS Git throws at its users, like:

```
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'github.com:Wilm0r/giggity.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Like, you know, when you provide a hint it's supposed to HELP instead of just being more faff about how your version control system internals are not meant for end users.